* DONE False positive for footnotes without text
  CLOSED: [2015-03-22 dom 09:09]
* DONE False positive for lists on right/center aligned text
  CLOSED: [2015-04-08 mer 11:20]

 This turned out to be more complicated then expected.

  - The parsing is done line by line without context
  - Storing the previous element and looking back is not going to help
    because the lines are not fully parsed yet
  - The list code is insane

This needs a refactoring when the parsing is done in context.

* DONE Category/Categories needs an override
  CLOSED: [2015-03-22 dom 12:42]
* DONE Clean soft-hyphen + space on typographical fixes
  CLOSED: [2015-03-22 dom 09:09]
* DONE Properly document lexicon.json
  CLOSED: [2015-04-08 mer 12:00]
* TODO When activating an user, send a mail
* TODO Add descriptions to categories

Db only, probably.

* TODO covers/decorative text image 

This kind of images kind of defeat the purpose of this engine, if we
store the crap in the git. But still, this is a common feature of all
the major blog engines. So maybe it should be stored in the db, and in
a public directory.

Same goes with the teaser, probably.


