#!/bin/sh

set -e

case "$1" in
    configure)
        # Create amusewiki system user
        getent passwd amusewiki > /dev/null || \
            adduser --quiet --system --home /var/lib/amusewiki  --no-create-home \
            --gecos 'Beanstalk Server' --group amusewiki

        ;;

    failed-upgrade|abort-upgrade|abort-remove|abort-deconfigure|in-favour|removing)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 1;
        ;;
esac

chown amusewiki:amusewiki /var/lib/amusewiki/


