#!/usr/bin/env perl

BEGIN { die "Do not run this as root" unless $>; }

use strict;
use warnings;

=pod

=head1 NAME

amusewiki-populate-webfonts - amusewiki helper for EPUB font embedding


=head1 SYNOPSIS

 amusewiki-populate-webfonts

Create the configuration file with font definitions.

It just calls C<muse-create-font-file.pl fontspec.json>

This script is meant to be used when creating an app directory.

=cut

system(qw/muse-create-font-file.pl fontspec.json/);


