#!/usr/bin/env perl

BEGIN { die "Do not run this as root" unless $>; }

use strict;
use warnings;
use utf8;
use AmuseWikiFarm::Schema;
use AmuseWikiFarm::Utils::Jobber;

=pod

=head1 NAME

amusewiki-jobber - amusewiki job daemon

=head1 SYNOPSIS

Daemon which takes care of all the slow amusewiki's operations. Needs
to be launched from the application's root, where the repo are located.

It stays in the foreground, but each job is managed in a double fork
(so killing it doesn't kill the grandchild).

=cut

my $schema = AmuseWikiFarm::Schema->connect('amuse');

# at startup, ensure all the sites will have fresh indexes. This will
# schedule the jobs. Wrapped in eval if DB is failing us.
eval {
    foreach my $site ($schema->resultset('Site')->all) {
        $site->generate_static_indexes;
    }
};

my $jobber = AmuseWikiFarm::Utils::Jobber->new(
                                               schema => $schema,
                                               ($ENV{AMW_POLLING} ?
                                                ( polling_interval => $ENV{AMW_POLLING} )
                                                :
                                                ()
                                               ));

while (1) {
    $jobber->main_loop;
}
    

