#!/usr/bin/env perl

BEGIN { die "Do not run this as root" unless $>; }
use utf8;
use strict;
use warnings;
use lib 'lib';
use AmuseWikiFarm::Schema;
use AmuseWikiFarm::Archive::OAI::PMH;
use File::Temp;
use YAML qw/LoadFile DumpFile/;
use Getopt::Long;
use Pod::Usage;
use Time::HiRes qw/gettimeofday tv_interval/;

my $help;
GetOptions(help => \$help) or die;

my (@site_ids) = @ARGV;

if ($help or !@site_ids) {
    pod2usage;
    exit 2;
}

my $schema = AmuseWikiFarm::Schema->connect('amuse');

foreach my $site ($schema->resultset('Site')->search({ id => \@site_ids })) {
    my $start = [ gettimeofday ];
    my $oai_pmh = AmuseWikiFarm::Archive::OAI::PMH->new(site => $site,
                                                        logger => sub {
                                                            my @lines = @_;
                                                            foreach my $l (@lines) {
                                                                print tv_interval($start) . " " . $l;
                                                            }
                                                        },
                                                       );
    my $time = time();
    $oai_pmh->update_site_records;
    print "Updated OAI-PMH records for " . $site->id . " in " . (time() - $time) . " seconds\n";
}


=pod

=encoding utf8

=head1 NAME

amusewiki-oai-pmh-index - Rebuild the OAI-PMH index

=head1 SYNOPSIS

 amusewiki-oai-pmh-index site_id_1 [ site_id_2, ...]

Mostly Used for debugging.

=cut


