#!/usr/bin/env perl

BEGIN { die "Do not run this as root" unless $>; }

use strict;
use warnings;
use lib 'lib';
use AmuseWikiFarm::Schema;
use File::Spec::Functions qw/catdir/;
use Getopt::Long;
use Pod::Usage;

my $schema = AmuseWikiFarm::Schema->connect('amuse');

=pod

=head1 NAME

amusewiki-letsencrypt - get SSL certificates from Let's encrypt

=head1 SYNOPSIS

amusewiki-letsencrypt [ --check-only --help ]

Update the acme certificates.

=cut

my $check_only = 0;
my $help = 0;

GetOptions("check-only" => \$check_only,
           "help" => \$help,
          ) or die;

if ($help) {
    pod2usage;
    exit 2;
}

my $updates = $schema->resultset('Site')->check_and_update_acme_certificates(!$check_only, 1);

print "Certificates installed: $updates\n";
