#!/usr/bin/env perl

BEGIN { die "Do not run this as root" unless $>; }

use strict;
use warnings;
use utf8;
use lib 'lib';
use AmuseWikiFarm::Schema;
use AmuseWikiMeta::Archive::Config;
use Path::Tiny;
use YAML qw/DumpFile/;

my $schema = AmuseWikiFarm::Schema->connect('amuse');

my $wd = Path::Tiny->tempdir(CLEANUP => 0);
my $out = $wd->child('amw-meta-config.yml');

my $conf = AmuseWikiMeta::Archive::Config->new(config_file => "$out",
                                               schema => $schema)->generate_config;
print "Configuration file left in $out\n";

__END__
=pod

=encoding utf8

=head1 NAME

amusewiki-generate-meta-config - generate a amw-meta-config.yml

=head1 SYNOPSIS

Usage: amusewiki-generate-meta-config 

Generate a meta config in a /tmp so you can grab it. 

=cut
