#!/usr/bin/env perl

use strict;
use warnings;
use utf8;
use lib 'lib';
use AmuseWikiFarm;

my $schema = AmuseWikiFarm->model('DB');

my @sites = $schema->resultset('Site')->active_only->all;

my $confgenerator = AmuseWikiFarm->model('Webserver');

=pod

=head1 NAME

amusewiki-generate-nginx-conf - generate nginx configuration files for amusewiki

=head1 SYNOPSIS

Generate a suitable nginx configuration and prints the activation
commands.

=cut


if (my $out = $confgenerator->generate_nginx_config(@sites)) {
    print "# please execute as root:\n";
    print $out;
}
