#!/usr/bin/env perl
use strict;
use warnings;
use FindBin qw/$Bin/;
use lib "$Bin/../lib";
use AmuseWikiFarm::Schema;
use Text::Amuse::Compile::Utils qw/read_file write_file/;
use File::Spec;

my $schema = AmuseWikiFarm::Schema->connect('amuse');

my @args = ($AmuseWikiFarm::Schema::VERSION, 'sql');

my $latest_version_file = File::Spec->catfile(sql => 'version.txt');

if (-f $latest_version_file) {
    my $v = read_file($latest_version_file);
    if ($AmuseWikiFarm::Schema::VERSION > $v) {
        push @args, $v;
    }
}

$schema->create_ddl_dir(['MySQL', 'SQLite', 'PostgreSQL'], @args);
write_file($latest_version_file, $AmuseWikiFarm::Schema::VERSION);


