#!/bin/sh

set -e
cd `dirname $0`
cd ..

tempdir=$1
if [ "x$tempdir" = "x" ]; then
    tempdir=`mktemp -d`
else
    mkdir -p $tempdir
fi

cat <<EOF > $tempdir/amusewiki-jobber.service
[Unit]
Description=Amusewiki jobber
After=nss-user-lookup.target

[Service]
WorkingDirectory=$(pwd)
User=$(whoami)
Group=$(whoami)
Environment="PATH=$PATH"
ExecStart=$(which carton) exec perl -I$(pwd)/lib $(pwd)/script/amusewiki-jobber
Restart=always

[Install]
WantedBy=multi-user.target

EOF

cat <<EOF > $tempdir/amusewiki-web.service
[Unit]
Description=Amusewiki web server
After=nss-user-lookup.target

[Service]
WorkingDirectory=$(pwd)
User=$(whoami)
Group=$(whoami)
Environment="PATH=$PATH"
ExecStart=$(which carton) exec plackup -s FCGI --listen $(pwd)/var/amw.sock --nproc 5 -E deployment $(pwd)/psgi/amusewiki.psgi
Restart=always

[Install]
WantedBy=multi-user.target

EOF

cat <<EOF> $tempdir/amusewiki-nginx-reload.path
[Unit]
Description=Path to monitor to trigger an nginx reload

[Path]
PathChanged=$(pwd)/ssl/amusewiki_requests_webserver_reload.txt

[Install]
WantedBy=multi-user.target
EOF

cat <<EOF> $tempdir/amusewiki-nginx-reload.service
[Unit]
Description=Trigger an nginx reload
Wants=nginx.service

[Service]
ExecStart=/bin/sh -c '/usr/sbin/nginx -t && /usr/sbin/service nginx reload'
EOF



head -100 $tempdir/*
echo "############################################"
cat <<EOF
# The above systemd unit files are ready to be installed

# Please execute as root:

EOF

for i in amusewiki-jobber.service \
             amusewiki-web.service \
             amusewiki-nginx-reload.path amusewiki-nginx-reload.service; do

    echo "cat $tempdir/$i > /etc/systemd/system/$i";
done

echo "systemctl daemon-reload"

for i in amusewiki-jobber.service amusewiki-web.service  amusewiki-nginx-reload.path; do
    echo "systemctl start $i"
    echo "systemctl enable $i"
done
