#!/bin/sh

filelist=`mktemp`

find ./lib -type f -iname "*.pm" | grep -v debug_loc > $filelist
find ./root/src -type f -iname "*.tt" | grep -v debug_loc >> $filelist
find ./mkits -type f >> $filelist
cat $filelist

xgettext.pl -P perl=* -P tt2=* \
    --output=lib/AmuseWikiFarm/I18N/messages.pot -f $filelist

for i in hr fi es mk ru it de fr nl en sq sr sv pl pt; do
    msgmerge --no-fuzzy-matching --update --no-location \
             lib/AmuseWikiFarm/I18N/$i.po \
             lib/AmuseWikiFarm/I18N/messages.pot
done

