name: linux

on:
  push:
    branches: ['*']
    tags-ignore: ['*']
  pull_request:
  
jobs:
 
# This step lists t/**.t, so that we can run the tests in a matrix on
# it in github. When you run each test as it's own step we get the
# results testing broken up into a nice list in the side bar, and
# github can schedule the test however it likes.
#
# It's worth noting that we skip having t/00-prepare-tests in this list because it is run
# before each test in the matrix.

  testlist: 
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.tests.outputs.files }}
    steps:
      - uses: actions/checkout@v5
      - id: tests
        run: |
          find t/ -type f -name '*.t' | \
          perl -MJSON::PP -nlE '
            push @files, $_ unless /00-prepare-tests.t/ 
            }{
            print "files=" . encode_json(\@files)
          ' >> "$GITHUB_OUTPUT"

  builddeb:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/melmothx/amusewiki-ci:trixie
    steps:
      - uses: actions/checkout@v5
      - name: install prerequisite
        run: |
          apt-get update && apt-get install bash-completion
      - name: build package
        run: |
          DEB_BUILD_OPTIONS=nocheck debuild -i -us -uc --pre-clean --post-clean -b
      - name: check package content
        run: |
          cd ..; for i in *.deb; do dpkg --contents $i; done; true

  test:
    needs: [ testlist, builddeb ]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        test_file: ${{ fromJson(needs.testlist.outputs.tests) }}

    container:
      image: ghcr.io/melmothx/amusewiki-ci:trixie

    steps:
      - uses: actions/checkout@v5

      - name: git config
        run: |
            git config --global user.email "im-sorry-my-ci-build-is-harssing-you-from@amusewiki.github.com"; 
            git config --global user.name "amusewiki CI build of $GITHUB_REF"
          
      - name: set PATH
        run: |
          echo "PATH=/opt/amusewiki-texlive/current/bin/arch:$PATH" >> $GITHUB_ENV

      - name: prove ${{ matrix.test_file }}
        run: |
          prove -lv t/00-prepare-tests.t ${{ matrix.test_file }}

